# Generated by Django 3.2.3 on 2021-06-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
