# Generated by Django 3.2.3 on 2021-06-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_comments_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='username',
        ),
    ]
