# Generated by Django 3.2.3 on 2021-06-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210609_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_post', 'Can add post'), ('can_manage_post', 'Can manage post'))},
        ),
        migrations.RemoveField(
            model_name='author',
            name='username',
        ),
    ]
